In [2]:
import numpy as np

array = np.arange(1,11)
array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
shapedarray = array.reshape(2,5)
shapedarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
shapedarray[1][2]

np.int64(8)

In [5]:
array_1 = np.array([10,20,30])
array_2 = np.array([1,2,3])

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)


[11 22 33]
[ 9 18 27]
[10 40 90]


In [6]:
summary_array = array_1 * array_2

print(summary_array.sum())
print(summary_array.mean())
print(summary_array.std())


140
46.666666666666664
32.99831645537222


In [7]:
one_d_array = np.arange(0,15).reshape(3,5)
one_d_array + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
another_array = np.arange(0,15).reshape(3,5)
print(another_array)
another_array * one_d_array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [9]:
new_array = np.array([15,22,33,41,50,65,72 ])

values_over_40 = new_array < 40

print(new_array[values_over_40])

new_array[new_array > 40 ]= 0
new_array

[15 22 33]


array([15, 22, 33,  0,  0,  0,  0])

In [11]:
matrix = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
matrix.transpose()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
matrix_2 = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix_3 = np.dot(matrix,matrix_2)
matrix_3

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [14]:
np.linalg.inv(matrix_3)

array([[ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14]])