In [7]:
import numpy as np

array = np.arange(1,11)
array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
shapedarray = array.reshape(2,5)
shapedarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
shapedarray[1][2]

np.int64(8)

In [13]:
array_1 = np.array([10,20,30])
array_2 = np.array([1,2,3])

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)


[11 22 33]
[ 9 18 27]
[10 40 90]


In [14]:
summary_array = array_1 * array_2

print(summary_array.sum())
print(summary_array.mean())
print(summary_array.std())


140
46.666666666666664
32.99831645537222


In [17]:
one_d_array = np.arange(0,15).reshape(3,5)
one_d_array + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
another_array = np.arange(0,15).reshape(3,5)
print(another_array)
another_array * one_d_array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [22]:
new_array = np.array([15,22,33,41,50,65,72 ])

values_over_40 = new_array < 40

print(new_array[values_over_40])

new_array[new_array > 40 ]= 0
new_array

[15 22 33]


array([15, 22, 33,  0,  0,  0,  0])